--- #YAML:1.0
name:               Math-BLAS
version:            1.00
abstract:           basic linear algebra subroutines
author:
    - Ralph Schleicher <rs@ralph-schleicher.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
